version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8090:8090"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - "D:/Programs/Jenkins_Docker:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
  postgres:
    image: postgres:9.6
    networks:
      - jenkins
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - "D:/Programs/Docker_Volumes/postgresql:/var/lib/postgresql/data"
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
      - postgres

networks:
  jenkins:


